### ISSUE TITLE
Error: hardware not supported RPi 4Gb

### ISSUE THREAD

**Issue by simonk3** [kgbplus/gpiotest#10]
Console throws an error:
pi@RPi:~ $ sudo python3 gpiotest.py.2
hardware not supported

any Idea what it could be?

**Comment by RomanMindlin** [comment]
What Raspberry Pi model do you have?

**Comment by tyjtyj** [comment]
i got this instead on pi4B 4G

```
root@raspberrypi:~# sudo python gpiotest.py  
Failed to add edge detection
```

**Comment by RiadySantoso82** [comment]
same with raspberry pi3B+, return error 'Failed to add edge detection'

**Comment by kgbplus** [comment]
Script trying to access busy gpio lines. Will be fixed soon

**Comment by RomanMindlin** [comment]
Created separate issue https://github.com/kgbplus/gpiotest/issues/10
