### ISSUE TITLE
Hardware Not Supported - RPI 4 8gb

### ISSUE THREAD

**Issue by joshschools** [kgbplus/gpiotest#13]
Receive Hardware Not Supported when running python script.

`pi@fluiddpi:~/gpiotest $ sudo python gpiotest.py --gpio_num 26
hardware not supported`
`pi@fluiddpi:~/gpiotest $ sudo python gpiotest.py --gpio_num 17
hardware not supported`
`pi@fluiddpi:~/gpiotest $ sudo python gpiotest.py
hardware not supported
`

**Comment by joshschools** [comment]
I added:
`"d03114": "4 Model B 8Gb"`
and
`"d03114": 26`
 to the script. Now I get the same error as #12 tried running the trouble shooting steps provided in that and still get the same error.

**Comment by RomanMindlin** [comment]
I accepted and merged your pull request. Thank you very much!
