### ISSUE TITLE
Trying in a Raspberry Pi 4

### ISSUE THREAD

**Issue by Mazuco** [kgbplus/gpiotest#4]
root@raspberrypi:~/gpiotest# python gpiotest.py 
hardware not supported
Traceback (most recent call last):
  File "gpiotest.py", line 399, in <module>
    termOn()
  File "gpiotest.py", line 39, in termOn
    curses.nocbreak()
_curses.error: must call initscr() first

**Comment by Mazuco** [comment]
-

**Comment by RomanMindlin** [comment]
Thank you for your report. I've updated hardware detection list.
