### ISSUE TITLE
RPi B+ v1.2 "not supported"

### ISSUE THREAD

**Issue by dertobes** [kgbplus/gpiotest#7]
My B+ identifies as "13" not "0013"
https://github.com/kgbplus/gpiotest/blob/9f776a96a877e2f0176cd7b918dc0ec45d4f8982/gpiotest.py#L242

**Comment by RomanMindlin** [comment]
If you edit this line and correct "0013" to "13" - does it helps?

**Comment by dertobes** [comment]
Yes. I fixed it for myself by adding a line with `'13'` but wanted give feedback so you can fix it for everyone.
Thanks for your work on this simple test tool!

**Comment by RomanMindlin** [comment]
Thank you very much for your feedback! I will fix it.
