### ISSUE TITLE
raspberry 2B+ no results GPIOtest

### ISSUE THREAD

**Issue by pvaan** [kgbplus/gpiotest#8]
Hello
I suspect I roasted one or more Gpoi-pins. Anyway SPI doesn't do its job like it used to, since I tried to measure battery voltage via Mcp3008 ADconverter
Gpio load spi gives gpio:unable to load/unload modules etc
Ls /dev/*spi* gives the two devices /dev/spidev0.0 and 0.1
Did raspi-config, dtparam=spi=on 
Lsmod gives no spidev anymore! But bcm2835_gpiomem is there.
Controled the settings several times, updated etc, no clue. So tried to test with Gpiotest.py.
sudo pigpiod but when I run the program in CL, i get no message and a new commandline after 1-2 seconds.
No message. What can be the background of this?
Is my SPI "broken"? If just Gpiotest would work!
I have a Rasberry 2B v.14 2014
Linux raspberry 4.1.19-v7+

Thanks

**Comment by RomanMindlin** [comment]
Not actually software issue. Closed
